"use client";

import React, { useState, useEffect } from 'react';
import { ethers } from 'ethers';
import Link from 'next/link';

// Import ABIs generated by Hardhat
import IdentityJSON from '../../../artifacts/contracts/Identity.sol/Identity.json';
import KYCGatedAuctionJSON from '../../../artifacts/contracts/KYCGatedAuction.sol/KYCGatedAuction.json';

// --- CONTRACT ADDRESSES ---
// In a real app, these might come from environment variables.
const IDENTITY_CONTRACT_ADDRESS = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0";
const AUCTION_CONTRACT_ADDRESS = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9";

const IDENTITY_ABI = IdentityJSON.abi;
const AUCTION_ABI = KYCGatedAuctionJSON.abi;

export default function AuctionPage() {
  // --- STATE MANAGEMENT ---
  const [walletAddress, setWalletAddress] = useState(null);
  const [isVerified, setIsVerified] = useState(false);
  
  const [auctionActive, setAuctionActive] = useState(false);
  const [highestBid, setHighestBid] = useState("0");
  const [highestBidder, setHighestBidder] = useState("");
  
  const [bidAmount, setBidAmount] = useState("");
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [successMsg, setSuccessMsg] = useState("");

  // Re-fetch data if wallet changes
  useEffect(() => {
    if (walletAddress) {
      checkVerification(walletAddress);
      fetchAuctionData();
    }
  }, [walletAddress]);

  // --- HELPER FUNCTIONS ---

  const connectWallet = async () => {
    setErrorMsg("");
    if (typeof window !== "undefined" && window.ethereum) {
      try {
        const provider = new ethers.BrowserProvider(window.ethereum);
        const signer = await provider.getSigner();
        const address = await signer.getAddress();
        setWalletAddress(address);
      } catch (error) {
        console.error("Wallet connection error:", error);
        setErrorMsg("Failed to connect wallet.");
      }
    } else {
      setErrorMsg("Please install MetaMask!");
    }
  };

  // 1) Composability Check: Interacting with IdentityVerifier separately
  const checkVerification = async (address) => {
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      const identityContract = new ethers.Contract(IDENTITY_CONTRACT_ADDRESS, IDENTITY_ABI, provider);
      
      // Call the identity contract to check KYC status
      const verifiedStatus = await identityContract.isVerified(address);
      setIsVerified(verifiedStatus);
    } catch (err) {
      console.error("Failed to check verification status:", err);
    }
  };

  // 2) Interacting with KYCGatedAuction separately
  const fetchAuctionData = async () => {
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      const auctionContract = new ethers.Contract(AUCTION_CONTRACT_ADDRESS, AUCTION_ABI, provider);
      
      const active = await auctionContract.auctionActive();
      setAuctionActive(active);

      const hBid = await auctionContract.highestBid();
      setHighestBid(ethers.formatEther(hBid));

      const hBidder = await auctionContract.highestBidder();
      setHighestBidder(hBidder === ethers.ZeroAddress ? "None" : hBidder);
    } catch(err) {
      console.error("Failed to fetch auction data:", err);
    }
  };

  const placeBid = async () => {
    setErrorMsg("");
    setSuccessMsg("");
    
    if (!bidAmount || isNaN(bidAmount) || Number(bidAmount) <= 0) {
      setErrorMsg("Please enter a valid bid amount.");
      return;
    }

    setLoading(true);
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      const signer = await provider.getSigner();
      const auctionContract = new ethers.Contract(AUCTION_CONTRACT_ADDRESS, AUCTION_ABI, signer);
      
      // Send the transaction with the bid value attached
      const tx = await auctionContract.placeBid({ value: ethers.parseEther(bidAmount) });
      await tx.wait(); // Wait for confirmation
      
      setSuccessMsg("Bid placed successfully!");
      setBidAmount("");
      
      // Refresh auction data to show new highest bid
      fetchAuctionData();
    } catch (error) {
      console.error("Bid error:", error);
      
      // Basic error parsing
      if (error.reason) {
        setErrorMsg(error.reason);
      } else if (error.message.includes("Bid too low")) {
         setErrorMsg("Bid too low. You must bid higher than the current highest bid.");
      } else if (error.message.includes("KYC required")) {
         setErrorMsg("KYC required. Your address is not verified.");
      } else if (error.message.includes("Auction not active")) {
         setErrorMsg("The auction is currently inactive.");
      } else {
         setErrorMsg("Failed to place bid. See console for details.");
      }
    }
    setLoading(false);
  };

  // --- RENDER UI ---
  return (
    <div className="min-h-screen bg-gray-50 p-8 font-sans text-gray-900">
      <div className="max-w-2xl mx-auto">
        
        {/* Navbar */}
        <nav className="flex justify-between items-center mb-8 bg-white p-4 rounded-lg shadow border">
          <Link href="/" className="text-blue-600 hover:underline font-semibold">
            ← Back to Home
          </Link>
          <button 
            onClick={connectWallet} 
            className={`px-4 py-2 rounded font-bold text-white transition-colors ${walletAddress ? 'bg-green-500 hover:bg-green-600' : 'bg-blue-600 hover:bg-blue-700'}`}
          >
            {walletAddress ? `Connected: ${walletAddress.substring(0,6)}...${walletAddress.slice(-4)}` : 'Connect Wallet'}
          </button>
        </nav>

        {/* Main Content Card */}
        <div className="bg-white rounded-xl shadow-lg border p-8">
          <h1 className="text-3xl font-bold mb-6 text-center text-gray-800">Exclusive NFT Auction</h1>
          
          {/* Notifications */}
          {errorMsg && <div className="mb-4 p-3 bg-red-100 border border-red-400 text-red-700 rounded">{errorMsg}</div>}
          {successMsg && <div className="mb-4 p-3 bg-green-100 border border-green-400 text-green-700 rounded">{successMsg}</div>}

          {/* Section 2: Verification Status */}
          <div className="mb-8 p-4 rounded-lg border bg-gray-50 flex justify-between items-center">
            <span className="font-semibold text-gray-700">KYC Verification Status:</span>
            {walletAddress ? (
              isVerified ? (
                <span className="px-3 py-1 bg-green-100 text-green-800 border border-green-300 rounded-full font-bold flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-green-600"></span> ✔ Verified
                </span>
              ) : (
                <span className="px-3 py-1 bg-red-100 text-red-800 border border-red-300 rounded-full font-bold flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-red-600"></span> ❌ Not Verified
                </span>
              )
            ) : (
              <span className="text-gray-500 italic">Connect wallet to check</span>
            )}
          </div>

          {/* Section 1: Auction Info */}
          <div className="grid grid-cols-2 gap-4 mb-8">
            <div className="p-4 bg-blue-50 rounded-lg border border-blue-100">
              <p className="text-sm text-blue-600 font-semibold mb-1">Status</p>
              <p className="text-xl font-bold text-gray-800">
                {auctionActive ? "🟢 Active" : "🔴 Inactive"}
              </p>
            </div>
            <div className="p-4 bg-blue-50 rounded-lg border border-blue-100">
              <p className="text-sm text-blue-600 font-semibold mb-1">Highest Bid</p>
              <p className="text-xl font-bold text-gray-800">{highestBid} ETH</p>
            </div>
            <div className="p-4 bg-blue-50 rounded-lg border border-blue-100 col-span-2">
              <p className="text-sm text-blue-600 font-semibold mb-1">Highest Bidder</p>
              <p className="text-md font-mono text-gray-700 break-all">
                {highestBidder}
              </p>
            </div>
          </div>

          {/* Section 3: Bid Input */}
          <div className="pt-6 border-t border-gray-200">
            <h3 className="text-lg font-bold mb-4 text-gray-800">Place a Bid</h3>
            <div className="flex gap-3">
              <input 
                type="number" 
                step="0.01"
                placeholder="Amount in ETH" 
                value={bidAmount}
                onChange={(e) => setBidAmount(e.target.value)}
                disabled={!auctionActive || !isVerified || loading}
                className="border border-gray-300 p-3 rounded-lg flex-1 focus:ring-2 focus:ring-blue-500 outline-none disabled:bg-gray-100" 
              />
              <button 
                onClick={placeBid} 
                disabled={!auctionActive || !isVerified || loading} 
                className={`px-6 py-3 rounded-lg font-bold text-white transition-colors 
                  ${(!auctionActive || !isVerified) ? 'bg-gray-400 cursor-not-allowed' : 'bg-blue-600 hover:bg-blue-700'}
                `}
              >
                {loading ? "Processing..." : "Place Bid"}
              </button>
            </div>
            
            {/* Conditional messaging for disabled states */}
            {walletAddress && !isVerified && (
              <p className="text-sm text-red-600 mt-3 font-semibold">
                * You must complete KYC to participate.
              </p>
            )}
            {walletAddress && isVerified && !auctionActive && (
              <p className="text-sm text-yellow-600 mt-3 font-semibold">
                * The auction is currently inactive.
              </p>
            )}
          </div>

        </div>
      </div>
    </div>
  );
}
