"use client";

import React, { useState, useEffect } from 'react';
import { ethers } from 'ethers';
import Link from 'next/link';
// Imports the ABI generated by Hardhat
import IdentityJSON from '../../artifacts/contracts/Identity.sol/Identity.json';

const CONTRACT_ADDRESS = "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0";
const ABI = IdentityJSON.abi;

export default function IdentityDApp() {
  const [activeTab, setActiveTab] = useState('user');
  const [walletAddress, setWalletAddress] = useState(null);
  const [userStatus, setUserStatus] = useState('Not Connected'); 
  const [isAdmin, setIsAdmin] = useState(false);
  const [isVerifier, setIsVerifier] = useState(false);
  
  // For UI testing purposes, we keep a mock list of users, 
  // but the actual approval/registration uses the real blockchain!
  const [pendingUsers, setPendingUsers] = useState([{ address: '0x1234...abcd', name: 'Alice (Mock)' }]);
  const [loading, setLoading] = useState(false);

  // --- BLOCKCHAIN CONNECTION ---
  const connectWallet = async () => {
    if (typeof window !== "undefined" && window.ethereum) {
      try {
        const provider = new ethers.BrowserProvider(window.ethereum);
        const signer = await provider.getSigner();
        const address = await signer.getAddress();
        
        setWalletAddress(address);
        await fetchUserBlockchainData(address, provider);
      } catch (error) {
        console.error("Wallet connection error:", error);
      }
    } else {
      alert("Please install MetaMask!");
    }
  };

  const fetchUserBlockchainData = async (address, provider) => {
    const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, provider);
    
    // 1. Check user verification status
    const status = await contract.userStatus(address);
    setUserStatus(status === "" ? "None" : status);

    // 2. Check if admin
    const adminAddress = await contract.admin();
    setIsAdmin(adminAddress.toLowerCase() === address.toLowerCase());

    // 3. Check if verifier
    const verifierStatus = await contract.isVerifier(address);
    setIsVerifier(verifierStatus);
  };

  // --- SMART CONTRACT WRITE FUNCTIONS ---
  const registerIdentity = async () => {
    if (!walletAddress) return alert("Connect wallet first");
    setLoading(true);
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      const signer = await provider.getSigner();
      const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, signer);
      
      // Hash of user data (In a real app, this is IPFS hash or actual data hash)
      const mockDataHash = "user_document_hash_123"; 
      
      const tx = await contract.registerIdentity(mockDataHash);
      await tx.wait(); // Wait for blockchain confirmation
      
      alert("Registration submitted to blockchain!");
      fetchUserBlockchainData(walletAddress, provider); // Refresh status
    } catch (error) {
      console.error(error);
      alert("Transaction failed or rejected.");
    }
    setLoading(false);
  };

  const approveUser = async (userAddressToApprove) => {
    setLoading(true);
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      const signer = await provider.getSigner();
      const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, signer);
      
      // We will just approve our own connected wallet for testing purposes
      const tx = await contract.approveUser(walletAddress);
      await tx.wait();
      
      alert("User Approved on Blockchain!");
      fetchUserBlockchainData(walletAddress, provider);
    } catch (error) {
      console.error(error);
      alert("Failed to approve. Are you sure you are a verifier and the user is 'Pending'?");
    }
    setLoading(false);
  };

  const makeMeVerifier = async () => {
    setLoading(true);
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      const signer = await provider.getSigner();
      const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, signer);
      
      const tx = await contract.addVerifier(walletAddress);
      await tx.wait();
      alert("You are now a verifier!");
      fetchUserBlockchainData(walletAddress, provider);
    } catch (error) {
      console.error(error);
      alert("Only the Admin can add verifiers.");
    }
    setLoading(false);
  };

  // --- UIs ---
  return (
    <div className="min-h-screen bg-gray-50 p-4 font-sans text-gray-900">
      <div className="max-w-4xl mx-auto">
        
        {/* Navbar */}
        <nav className="flex justify-between items-center p-4 bg-gray-900 text-white mb-8 rounded-lg shadow-md">
          <div className="flex gap-4">
            <button onClick={() => setActiveTab('user')} className={`px-3 py-1 rounded ${activeTab === 'user' ? 'bg-blue-600' : 'hover:bg-gray-700'}`}>User UI</button>
            <button onClick={() => setActiveTab('verifier')} className={`px-3 py-1 rounded ${activeTab === 'verifier' ? 'bg-blue-600' : 'hover:bg-gray-700'}`}>Verifier UI</button>
            <button onClick={() => setActiveTab('admin')} className={`px-3 py-1 rounded ${activeTab === 'admin' ? 'bg-blue-600' : 'hover:bg-gray-700'}`}>Admin UI</button>
            <Link href="/auction" className="px-3 py-1 rounded hover:bg-gray-700 flex items-center">Auction Page</Link>
          </div>
          <button onClick={connectWallet} className={`px-4 py-2 rounded font-bold ${walletAddress ? 'bg-green-500' : 'bg-blue-500'}`}>
            {walletAddress ? `Connected: ${walletAddress.substring(0,6)}...` : 'Connect Wallet'}
          </button>
        </nav>

        {/* 1. USER UI */}
        {activeTab === 'user' && (
          <div className="p-6 bg-white rounded-lg shadow border">
            <h2 className="text-2xl font-bold mb-4">Identity Registration</h2>
            <div className="mb-6 p-4 rounded bg-gray-100 flex justify-between items-center">
              <span className="font-semibold">Blockchain Status:</span>
              <span className="px-3 py-1 rounded font-bold bg-gray-300 text-gray-800">{userStatus}</span>
            </div>
            {(userStatus === 'None' || userStatus === 'Not Connected') && (
              <div className="flex flex-col gap-3">
                <input type="text" placeholder="Full Name" className="border p-2 rounded" />
                <button onClick={registerIdentity} disabled={loading} className="bg-blue-600 text-white py-2 rounded font-bold hover:bg-blue-700">
                  {loading ? "Processing..." : "Submit to Blockchain"}
                </button>
              </div>
            )}
          </div>
        )}

        {/* 2. VERIFIER UI */}
        {activeTab === 'verifier' && (
          <div className="p-6 bg-white rounded-lg shadow border">
            <h2 className="text-2xl font-bold mb-4 text-purple-700">Verifier Dashboard</h2>
            {isVerifier ? (
              <table className="w-full border-collapse">
                <thead><tr className="bg-gray-100"><th className="p-3">User</th><th className="p-3">Action</th></tr></thead>
                <tbody>
                  <tr className="border-b">
                    <td className="p-3">Your Wallet (Test Approval)</td>
                    <td className="p-3">
                      <button onClick={approveUser} disabled={loading} className="bg-green-500 text-white px-3 py-1 rounded font-bold">
                        {loading ? "Approving..." : "Approve on Blockchain"}
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            ) : (
              <p className="text-red-500 font-bold">Access Denied: You are not an authorized verifier.</p>
            )}
          </div>
        )}

        {/* 3. ADMIN UI */}
        {activeTab === 'admin' && (
          <div className="p-6 bg-white rounded-lg shadow border">
            <h2 className="text-2xl font-bold mb-4 text-red-700">Admin Control Panel</h2>
            {isAdmin ? (
              <div className="p-4 bg-red-50 border border-red-200 rounded">
                <p className="mb-4 text-sm text-gray-700">As the admin, you can authorize wallets to become verifiers.</p>
                <button onClick={makeMeVerifier} disabled={loading} className="bg-gray-900 text-white px-4 py-2 rounded font-bold">
                  {loading ? "Processing..." : "Make My Wallet A Verifier"}
                </button>
              </div>
            ) : (
              <p className="text-red-500 font-bold">Access Denied: You are not the contract admin.</p>
            )}
          </div>
        )}

      </div>
    </div>
  );
}