"use client";

import React, { useState, useEffect } from 'react';
import { ethers } from 'ethers';
import Link from 'next/link';
// Imports the ABI generated by Hardhat
import IdentityVerifierJSON from '../../artifacts/contracts/Identity.sol/IdentityVerifier.json';

const CONTRACT_ADDRESS = "0x0165878A594ca255338adfa4d48449f69242Eb8F";
const ABI = IdentityVerifierJSON.abi;

export default function IdentityDApp() {
  const [activeTab, setActiveTab] = useState('user');
  const [walletAddress, setWalletAddress] = useState(null);
  const [userStatus, setUserStatus] = useState('Not Connected'); 
  const [isAdmin, setIsAdmin] = useState(false);
  const [isVerifier, setIsVerifier] = useState(false);
  const [loading, setLoading] = useState(false);

  // --- BLOCKCHAIN CONNECTION ---
  const connectWallet = async () => {
    if (typeof window !== "undefined" && window.ethereum) {
      try {
        const provider = new ethers.BrowserProvider(window.ethereum);
        const signer = await provider.getSigner();
        const address = await signer.getAddress();
        
        setWalletAddress(address);
        await fetchUserBlockchainData(address, provider);
      } catch (error) {
        console.error("Wallet connection error:", error);
      }
    } else {
      alert("Please install MetaMask!");
    }
  };

  const fetchUserBlockchainData = async (address, provider) => {
    try {
      const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, provider);
      
      // 1. Check user verification status
      const identity = await contract.getIdentity(address);
      const statusNames = ["None", "Verified", "Revoked"];
      // status is returned as bigint or number from ethers v6. convert to Number()
      setUserStatus(statusNames[Number(identity.status)]);

      // 2. Check if admin
      const DEFAULT_ADMIN_ROLE = await contract.DEFAULT_ADMIN_ROLE();
      const isAdminRole = await contract.hasRole(DEFAULT_ADMIN_ROLE, address);
      setIsAdmin(isAdminRole);

      // 3. Check if verifier
      const VERIFIER_ROLE = await contract.VERIFIER_ROLE();
      const verifierStatus = await contract.hasRole(VERIFIER_ROLE, address);
      setIsVerifier(verifierStatus);
    } catch (error) {
      console.error("Failed to fetch contract data:", error);
      alert("Failed to read from the smart contract. Ensure MetaMask is on Localhost 8545.");
    }
  };

  // --- SMART CONTRACT WRITE FUNCTIONS ---
  const approveUser = async (userAddressToApprove) => {
    if (!userAddressToApprove) return alert("Please enter a user address");
    setLoading(true);
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      const signer = await provider.getSigner();
      const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, signer);
      
      const mockIdentityHash = ethers.id("some-unique-document-hash-" + Date.now()); // Generate a unique hash
      const tx = await contract.verifyIdentity(userAddressToApprove, mockIdentityHash);
      await tx.wait();
      
      alert(`User ${userAddressToApprove} Verified on Blockchain!`);
      fetchUserBlockchainData(walletAddress, provider);
    } catch (error) {
      console.error(error);
      alert("Failed to verify user. Are you sure you are a verifier?");
    }
    setLoading(false);
  };

  const grantVerifierRole = async () => {
    setLoading(true);
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      const signer = await provider.getSigner();
      const contract = new ethers.Contract(CONTRACT_ADDRESS, ABI, signer);
      
      const VERIFIER_ROLE = await contract.VERIFIER_ROLE();
      const tx = await contract.grantRole(VERIFIER_ROLE, walletAddress);
      await tx.wait();
      alert("You have been granted VERIFIER_ROLE!");
      fetchUserBlockchainData(walletAddress, provider);
    } catch (error) {
      console.error(error);
      alert("Only the Admin (DEFAULT_ADMIN_ROLE) can grant roles.");
    }
    setLoading(false);
  };

  // --- UIs ---
  return (
    <div className="min-h-screen bg-gray-50 p-4 font-sans text-gray-900">
      <div className="max-w-4xl mx-auto">
        
        {/* Navbar */}
        <nav className="flex justify-between items-center p-4 bg-gray-900 text-white mb-8 rounded-lg shadow-md">
          <div className="flex gap-4">
            <button onClick={() => setActiveTab('user')} className={`px-3 py-1 rounded ${activeTab === 'user' ? 'bg-blue-600' : 'hover:bg-gray-700'}`}>User UI</button>
            <button onClick={() => setActiveTab('verifier')} className={`px-3 py-1 rounded ${activeTab === 'verifier' ? 'bg-blue-600' : 'hover:bg-gray-700'}`}>Verifier UI</button>
            <button onClick={() => setActiveTab('admin')} className={`px-3 py-1 rounded ${activeTab === 'admin' ? 'bg-blue-600' : 'hover:bg-gray-700'}`}>Admin UI</button>
            <Link href="/auction" className="px-3 py-1 rounded hover:bg-gray-700 flex items-center">Auction Page</Link>
          </div>
          <button onClick={connectWallet} className={`px-4 py-2 rounded font-bold ${walletAddress ? 'bg-green-500' : 'bg-blue-500'}`}>
            {walletAddress ? `Connected: ${walletAddress.substring(0,6)}...` : 'Connect Wallet'}
          </button>
        </nav>

        {/* 1. USER UI */}
        {activeTab === 'user' && (
          <div className="p-6 bg-white rounded-lg shadow border">
            <h2 className="text-2xl font-bold mb-4">Identity Status</h2>
            <div className="mb-6 p-4 rounded bg-gray-100 flex justify-between items-center">
              <span className="font-semibold">Blockchain Status:</span>
              <span className="px-3 py-1 rounded font-bold bg-gray-300 text-gray-800">{userStatus}</span>
            </div>
            {userStatus !== 'Verified' && (
              <div className="flex flex-col gap-3">
                <p className="text-gray-600">Your identity needs to be verified by a Verifier.</p>
                <button 
                  disabled={true} 
                  className="bg-gray-400 text-white py-2 rounded font-bold cursor-not-allowed"
                >
                  Request Verification (Disabled)
                </button>
              </div>
            )}
            {userStatus === 'Verified' && (
              <button 
                onClick={() => alert("Functionality to revoke identity is not implemented yet.")} 
                className="bg-red-600 text-white py-2 rounded font-bold hover:bg-red-700"
              >
                Revoke My Identity
              </button>
            )}
          </div>
        )}

        {/* 2. VERIFIER UI */}
        {activeTab === 'verifier' && (
          <div className="p-6 bg-white rounded-lg shadow border">
            <h2 className="text-2xl font-bold mb-4 text-purple-700">Verifier Dashboard</h2>
            {isVerifier ? (
              <div className="p-4 bg-gray-100 rounded">
                <p className="text-gray-700 mb-2">As a Verifier, you can verify user identities.</p>
                <input 
                  type="text" 
                  placeholder="User Address to Verify (e.g., 0x...)" 
                  className="border p-2 rounded w-full mb-3" 
                  id="userToVerify" 
                />
                <button 
                  onClick={() => approveUser(document.getElementById('userToVerify').value)} 
                  disabled={loading} 
                  className="bg-green-500 text-white px-4 py-2 rounded font-bold hover:bg-green-600"
                >
                  {loading ? "Verifying..." : "Verify User"}
                </button>
              </div>
            ) : (
              <p className="text-red-500 font-bold">Access Denied: You do not have the VERIFIER_ROLE.</p>
            )}
          </div>
        )}

        {/* 3. ADMIN UI */}
        {activeTab === 'admin' && (
          <div className="p-6 bg-white rounded-lg shadow border">
            <h2 className="text-2xl font-bold mb-4 text-red-700">Admin Control Panel</h2>
            {isAdmin ? (
              <div className="p-4 bg-red-50 border border-red-200 rounded">
                <p className="mb-4 text-sm text-gray-700">As the admin (DEFAULT_ADMIN_ROLE), you can grant VERIFIER_ROLE to wallets.</p>
                <button onClick={grantVerifierRole} disabled={loading} className="bg-gray-900 text-white px-4 py-2 rounded font-bold">
                  {loading ? "Processing..." : "Grant My Wallet VERIFIER_ROLE"}
                </button>
              </div>
            ) : (
              <p className="text-red-500 font-bold">Access Denied: You do not have the DEFAULT_ADMIN_ROLE.</p>
            )}
          </div>
        )}

      </div>
    </div>
  );
}